package unauthorizedUser;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.function.Function;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

// niktovicd@gmail.com
// tBy%mvW8s#*CDrhb

public class AuthTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        driver.get("https://www.xing.com/");

        try{
            driver.findElement(By.xpath("//*[@id=\"consent-accept-button\"]")).click();
        } catch (org.openqa.selenium.NoSuchElementException ignored) {
            ;
        }
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void goodAuthorizationTest() {
        var wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        String login = "niktovicd@gmail.com";
        String password = "tBy%mvW8s#*CDrhb";

        driver.findElement(By.xpath("//*[@id=\"javascript-content\"]/div[1]/header/div/nav/a[1]")).click();
        driver.findElement(By.xpath("//*[@id=\"username\"]")).click();
        driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys(login);
        driver.findElement(By.xpath("//*[@id=\"password\"]")).click();
        driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys(password);
        driver.findElement(By.cssSelector(".erMSDu .buttonstyles__Text-sc-6z95j0-5")).click();
        js.executeScript("window.scrollTo(0,0)");

        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div/nav/ul/li[1]/a/p[1]")));
        assertThat(driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div/nav/ul/li[1]/a/p[1]")).getText(), is("Home"));
    }


    @Test
    public void badAuthorizationTest() {
        var wait = new WebDriverWait(driver, Duration.ofSeconds(20));

        String login = "badlogin";
        String password = "badpwd";

        driver.findElement(By.xpath("//*[@id=\"javascript-content\"]/div[1]/header/div/nav/a[1]")).click();
        driver.findElement(By.xpath("//*[@id=\"username\"]")).click();
        driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys(login);
        driver.findElement(By.xpath("//*[@id=\"password\"]")).click();
        driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys(password);
        driver.findElement(By.cssSelector(".erMSDu .buttonstyles__Text-sc-6z95j0-5")).click();
        js.executeScript("window.scrollTo(0,0)");

        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div[2]/div/div[2]/section/div/main/div/div/div/div/div[2]/form/div[4]/div/div/p/span")));
        assertThat(driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/div[2]/section/div/main/div/div/div/div/div[2]/form/div[4]/div/div/p/span")).getText(), is("Please check your login details and try again."));
    }
}
