package unauthorizedUser;// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.function.Function;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
public class InterfaceLanguageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void interfaceLanguage() {
    var wait = new WebDriverWait(driver, Duration.ofSeconds(20));
    driver.get("https://xing.com");
    try {driver.findElement(By.xpath("//*[@id=\"consent-accept-button\"]")).click();}
    catch (org.openqa.selenium.NoSuchElementException ignored) {}

    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/div[1]/div[2]/div/footer/div[2]/div/nav/div/a")));
    driver.findElement(By.xpath("/html/body/div[1]/div[2]/div/footer/div[2]/div/nav/div/a")).click();
    js.executeScript("window.scrollTo(0,0)");
    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\"javascript-content\"]/div[2]/div/div[2]/div/div[3]/a")));
    driver.findElement(By.xpath("//*[@id=\"javascript-content\"]/div[2]/div/div[2]/div/div[3]/a")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\"javascript-content\"]/div[1]/header/div/nav/a[2]/div/span")).getText(), is("Registrarse"));
  }
}
